- name: Ensure required libraries are installed
  ansible.builtin.include_role:
    name: roles/utils/os/packages/installed
  vars:
    utils_os_packages_installed__packages: "{{ games_battlefield_1942_server_installed__libraries }}"

- name: Ensure Existence of Service User
  ansible.builtin.include_role:
    name: roles/utils/os/users/service/created
  vars:
    - utils_os_users_service_created__group: "{{ games_battlefield_1942_server_installed__group }}"
    - utils_os_users_service_created__user: "{{ games_battlefield_1942_server_installed__user }}"

- name: Ensure permissions on target directories
  ansible.builtin.include_role:
    name: roles/utils/os/users/service/directory/permissions/granted
  vars:
    utils_os_users_service_directory_permissions_granted__user: "{{ games_battlefield_1942_server_installed__user }}"
    utils_os_users_service_directory_permissions_granted__group: "{{ games_battlefield_1942_server_installed__group }}"
    utils_os_users_service_directory_permissions_granted__directories: "{{ games_battlefield_1942_server_installed__service_directories }}"

- name: Ensure Environment Variables are properly set
  ansible.builtin.include_role:
    name: roles/utils/os/users/service/environment/variables/persisted
  vars:
    - utils_os_users_service_environment_variables_persisted__user: "{{ games_battlefield_1942_server_installed__user }}"
    - utils_os_users_service_environment_variables_persisted__group: "{{ games_battlefield_1942_server_installed__group }}"
    - utils_os_users_service_environment_variables_persisted__service_dir: "{{ games_battlefield_1942_server_installed__directory }}"

- name: Ensure expected archives are extracted
  ansible.builtin.include_role:
    name: roles/utils/os/file/archive/download_and_extract
  vars:
    utils_os_file_archive_download_and_extract__user: "{{ games_battlefield_1942_server_installed__user }}"
    utils_os_file_archive_download_and_extract__group: "{{ games_battlefield_1942_server_installed__group }}"
    utils_os_file_archive_download_and_extract__src: "{{ item.src }}"
    utils_os_file_archive_download_and_extract__file_name: "{{ item.file_name }}"
    utils_os_file_archive_download_and_extract__dest: "{{ item.dest }}"
    utils_os_file_archive_download_and_extract__strip_top_level: "{{ item.strip_top | default(false) }}"
  loop: "{{ games_battlefield_1942_server_installed__archives }}"

- name: Ensure Symbolic Links
  ansible.builtin.include_role:
    name: roles/utils/os/file/links/symbolic/enforced
  vars:
    utils_os_file_links_symbolic_enforced__user: "{{ games_battlefield_1942_server_installed__user }}"
    utils_os_file_links_symbolic_enforced__group: "{{ games_battlefield_1942_server_installed__group }}"
    utils_os_file_links_symbolic_enforced__links: "{{ games_battlefield_1942_server_installed__symlinks }}"

- name: Enforce individual Instance con Templates
  become: true
  become_user: root
  ansible.builtin.template:
    src: templates/games/bf1942/mods/bf1942/settings/serversettings.con.j2
    dest: "{{ (games_battlefield_1942_server_installed__settings, 'serversettings.con') | ansible.builtin.path_join }}"
    owner: "{{ games_battlefield_1942_server_installed__user }}"
    group: "{{ games_battlefield_1942_server_installed__group }}"
    mode: '0644'
    backup: yes
  loop: "{{ games_battlefield_1942_server_installed__instances }}"

- name: Enforce maplist
  become: true
  become_user: root
  ansible.builtin.template:
    src: templates/games/bf1942/mods/bf1942/settings/maplist.con.j2
    dest: "{{ (games_battlefield_1942_server_installed__settings, 'maplist.con') | ansible.builtin.path_join }}"
    owner: "{{ games_battlefield_1942_server_installed__user }}"
    group: "{{ games_battlefield_1942_server_installed__group }}"
    mode: '0644'
    backup: yes

- name: Create systemd service files for BF Vietnam Server Instances
  ansible.builtin.include_role:
    name: roles/utils/os/systemd/service/configured
  vars:
    utils_os_systemd_service_configured__service_name: "{{ item.systemd_name }}"
    utils_os_systemd_service_configured__service_description: "{{ item.systemd_description }}"
    utils_os_systemd_service_configured__user: "{{ games_battlefield_1942_server_installed__user }}"
    utils_os_systemd_service_configured__group: "{{ games_battlefield_1942_server_installed__group }}"
    utils_os_systemd_service_configured__ld_library_path_string: "{{ games_battlefield_1942_server_installed__ld_library_path_string }}"
    utils_os_systemd_service_configured__execstart: "{{ item.execstart }}"
    utils_os_systemd_service_configured__working_directory: "{{ games_battlefield_1942_server_installed__directory }}"
    utils_os_systemd_service_configured__pseudo_tty: true
  loop: "{{ games_battlefield_1942_server_installed__instances }}"